#!/usr/bin/env sh
aws ecs register-task-definition --cli-input-json file:///home/sami/projects/website/commands/cyborg-dashboard-def.json
aws ecs update-service --cluster=lightpay --service=website --task-definition=website
